#!/bin/bash

Date=`date +'%d_%m_%Y'`
Time=`date +%H_%M_%S`
Dst="/Trash/$Date"
mkdir -p $Dst
for arg in "$@"
do
file=$(basename $arg)
mv $arg "$Dst/${Time}_${file}"
echo  "Moved to $Dst/${Time}_${file}"
done
